# -*- coding: utf-8 -*-
"""HW2_ตัวช่วยทำการบ้าน.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vwBFeQGu8ld_APqYZ0jaaLmJp5goWA2q
"""

import math 
def term_k(x,k):
    return ((-1) ** k) * (x ** (2*k + 1)) / math.factorial(2*k + 1)

def approximated_sin(x, m):
    return sum([term_k(x, k) for k in range(0, m+1)])

def find_eff(a,b):
    return math.sqrt((a-b) ** 2) # abs(a-b)

x = 8 # |x| ที่ต้องการ
m = 0 # ค่าที่น้อยที่สุดที่ทำให้ ผิดพลาดไม่เกิน 10**(-6)

while find_eff(math.sin(x), approximated_sin(x, m)) >= 10 ** (-6): m += 1;
print("x =", x, "-->", "m = ", m);